export {default as Header} from './header/Header';
export {default as About} from './about/About';
export {default as Skills} from './skills/Skills';
export {default as Services} from './services/Services';
export {default as Contact} from './contact/Contact';
export {default as Experience} from './experience/Experience';
export {default as Portfolio} from './portfolio/Portfolio';
export {default as Testimonial} from './testimonials/Testimonial'
export {default as Footer} from './footer/Footer'